package com.nogal.formicary.datagen;

import com.nogal.formicary.Formicary;
import com.nogal.formicary.item.ModItems;

import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.client.model.generators.ItemModelProvider;
import net.neoforged.neoforge.client.model.generators.ModelFile;
import net.neoforged.neoforge.common.data.ExistingFileHelper;

/**
 * Item models: a block-item parent (referencing the block model generated by
 * {@link ModBlockStateProvider}) for all 16 M1 blocks, plus a flat sprite for resin.
 *
 * <p>Uses {@link ModelFile.UncheckedModelFile} rather than {@code withExistingParent}
 * for the block-item parents so this provider doesn't depend on run order against
 * {@code ModBlockStateProvider} within the same {@code GatherDataEvent} -- the path is
 * fully known ahead of time ({@code formicary:block/<name>}, matching the model
 * {@link ModBlockStateProvider} generates for every M1 block).
 */
public class ModItemModelProvider extends ItemModelProvider {
    public ModItemModelProvider(PackOutput output, ExistingFileHelper existingFileHelper) {
        super(output, Formicary.MODID, existingFileHelper);
    }

    @Override
    protected void registerModels() {
        blockItem("packed_soil");
        blockItem("amber_earth");
        blockItem("deep_loam");
        blockItem("hardened_soil");
        blockItem("resin_block");
        blockItem("amber_glass");
        blockItem("fungal_bloom");
        blockItem("fungal_carpet");
        blockItem("brood_comb");
        blockItem("royal_comb");
        blockItem("provision_comb");
        blockItem("egg_cluster");
        blockItem("daylight_membrane");
        blockItem("anthill_soil");
        blockItem("anthill_core");
        blockItem("queens_crest");

        basicItem(ModItems.RESIN.get());
        basicItem(ModItems.CHITIN.get());
        // Round-4 play-test revision, item 3: flat sprite, same as every other plain item
        // in this list -- the PNG itself is a separate art task.
        basicItem(ModItems.CHITIN_PLATE.get());
        basicItem(ModItems.LARVA.get());
        // M8: a flat sprite, like every other seed item -- not a block-item parent, since
        // fungal_spores places fungal_spore_crop, a different block from its own name.
        basicItem(ModItems.FUNGAL_SPORES.get());
        basicItem(ModItems.ROYAL_JELLY.get());
        basicItem(ModItems.SCENT_GLAND.get());
        basicItem(ModItems.TRAIL_PHEROMONE.get());
        basicItem(ModItems.ROYAL_PHEROMONE_GLAND.get());
        basicItem(ModItems.PHEROMONE_HORN.get());
        basicItem(ModItems.HONEYED_COMB.get());
        basicItem(ModItems.FUNGAL_STEW.get());
        basicItem(ModItems.ROYAL_JELLY_TREAT.get());

        basicItem(ModItems.CHITIN_HELMET.get());
        basicItem(ModItems.CHITIN_CHESTPLATE.get());
        basicItem(ModItems.CHITIN_LEGGINGS.get());
        basicItem(ModItems.CHITIN_BOOTS.get());

        // Ep2 play-test revision (WP-1 item 2): Mandible Pickaxe + Pincer Sword replace the
        // five-tool Ep2 H1 set, same vanilla item/handheld parent (a flat sprite held at an
        // angle in-hand), not item/generated -- the same template every vanilla tool uses,
        // verified against the client-extra jar's assets/minecraft/models/item/*_sword.json
        // shape.
        handheldItem("mandible_pickaxe");
        handheldItem("pincer_sword");

        // Spawn eggs reuse the vanilla two-layer template; the shell/spot colours come
        // from DeferredSpawnEggItem's tint handler, not from a texture of our own.
        withExistingParent("worker_ant_spawn_egg", "item/template_spawn_egg");
        withExistingParent("soldier_ant_spawn_egg", "item/template_spawn_egg");
        withExistingParent("larva_spawn_egg", "item/template_spawn_egg");
        // Play-test round 1, spec item 5.
        withExistingParent("queen_ant_spawn_egg", "item/template_spawn_egg");
        // Round-4 play-test revision, item 5: reverses ENDER_ANT's own "deliberately no
        // spawn egg" call -- see ModEntities.ENDER_ANT_SPAWN_EGG. Same template, no
        // texture of our own, same as the four eggs above.
        withExistingParent("ender_ant_spawn_egg", "item/template_spawn_egg");

        // Ep2 task H3: decorative families. Base blocks, stairs and slabs all parent
        // the block model at their own name (blockItem() -- the stairs/slab "bottom"
        // model ModBlockStateProvider generates is written at exactly that path, the
        // same convention vanilla's own oak_stairs.json/oak_slab.json items use).
        //
        // Ep2 play-test revision (WP-1 item 4): packed_soil_brick_wall (and its
        // wallItem() helper, the only caller) removed -- the family's item set is now
        // base + stairs + slab only.
        blockItem("packed_soil_bricks");
        blockItem("packed_soil_brick_stairs");
        blockItem("packed_soil_brick_slab");

        blockItem("hardened_soil_tiles");
        blockItem("hardened_soil_tile_stairs");
        blockItem("hardened_soil_tile_slab");

        blockItem("polished_resin");
        blockItem("polished_resin_stairs");
        blockItem("polished_resin_slab");
    }

    private void blockItem(String name) {
        getBuilder(name).parent(new ModelFile.UncheckedModelFile(modLoc("block/" + name)));
    }

    private void handheldItem(String name) {
        withExistingParent(name, "item/handheld").texture("layer0", modLoc("item/" + name));
    }
}
