package com.nogal.formicary.datagen;

import com.nogal.formicary.Formicary;
import com.nogal.formicary.item.ModItems;

import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.client.model.generators.ItemModelProvider;
import net.neoforged.neoforge.client.model.generators.ModelFile;
import net.neoforged.neoforge.common.data.ExistingFileHelper;

/**
 * Item models: a block-item parent (referencing the block model generated by
 * {@link ModBlockStateProvider}) for all 16 M1 blocks, plus a flat sprite for resin.
 *
 * <p>Uses {@link ModelFile.UncheckedModelFile} rather than {@code withExistingParent}
 * for the block-item parents so this provider doesn't depend on run order against
 * {@code ModBlockStateProvider} within the same {@code GatherDataEvent} -- the path is
 * fully known ahead of time ({@code formicary:block/<name>}, matching the model
 * {@link ModBlockStateProvider} generates for every M1 block).
 */
public class ModItemModelProvider extends ItemModelProvider {
    public ModItemModelProvider(PackOutput output, ExistingFileHelper existingFileHelper) {
        super(output, Formicary.MODID, existingFileHelper);
    }

    @Override
    protected void registerModels() {
        blockItem("packed_soil");
        blockItem("amber_earth");
        blockItem("deep_loam");
        blockItem("hardened_soil");
        blockItem("resin_weep");
        blockItem("resin_block");
        blockItem("amber_glass");
        blockItem("fungal_bloom");
        blockItem("fungal_carpet");
        blockItem("brood_comb");
        blockItem("royal_comb");
        blockItem("egg_cluster");
        blockItem("daylight_membrane");
        blockItem("anthill_soil");
        blockItem("anthill_core");
        blockItem("queens_crest");

        basicItem(ModItems.RESIN.get());
        basicItem(ModItems.CHITIN.get());
        basicItem(ModItems.LARVA.get());
        basicItem(ModItems.ROYAL_JELLY.get());
        basicItem(ModItems.SCENT_GLAND.get());
        basicItem(ModItems.TRAIL_PHEROMONE.get());
        basicItem(ModItems.ROYAL_PHEROMONE_GLAND.get());
        basicItem(ModItems.PHEROMONE_HORN.get());

        basicItem(ModItems.CHITIN_HELMET.get());
        basicItem(ModItems.CHITIN_CHESTPLATE.get());
        basicItem(ModItems.CHITIN_LEGGINGS.get());
        basicItem(ModItems.CHITIN_BOOTS.get());

        // Spawn eggs reuse the vanilla two-layer template; the shell/spot colours come
        // from DeferredSpawnEggItem's tint handler, not from a texture of our own.
        withExistingParent("worker_ant_spawn_egg", "item/template_spawn_egg");
        withExistingParent("soldier_ant_spawn_egg", "item/template_spawn_egg");
        withExistingParent("larva_spawn_egg", "item/template_spawn_egg");
    }

    private void blockItem(String name) {
        getBuilder(name).parent(new ModelFile.UncheckedModelFile(modLoc("block/" + name)));
    }
}
