package com.nogal.formicary.datagen;

import java.util.function.Supplier;

import com.nogal.formicary.Formicary;
import com.nogal.formicary.sound.ModSounds;

import net.minecraft.data.PackOutput;
import net.minecraft.sounds.SoundEvent;
import net.minecraft.sounds.SoundEvents;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import net.neoforged.neoforge.common.data.SoundDefinition;
import net.neoforged.neoforge.common.data.SoundDefinitionsProvider;

/**
 * Generates {@code assets/formicary/sounds.json} -- the single file that decides what every
 * mod sound event in {@link ModSounds} actually plays.
 *
 * <p><b>Two kinds of entry live here.</b> The worker ant, soldier ant and queen have real
 * audio and use {@link #voice}; everything else is still a {@code type: "event"} redirect
 * via {@link #borrow}, resolving to the vanilla sound event that mob used to call directly.
 * A redirect ships no {@code .ogg} at all, which is what let this scaffolding exist before
 * any audio did. To promote one, swap its {@code borrow(...)} line for a {@code voice(...)}
 * line naming the files.
 *
 * <p><b>The audio itself is generated, not hand-exported.</b> The three mobs' files come
 * out of {@code assets-src/sounds.py}, which cuts them from Logan's raw recordings in
 * {@code assets-src/audio-src/}; the resources tree is build output. Changing how a voice
 * sounds means editing that script's table and re-running it, then {@code .\gradlew
 * runData}. Full walkthrough: {@code docs/SOUNDS.md}.
 *
 * <p><b>Why EVENT and not SOUND.</b> {@code SoundDefinitionsProvider#validate} runs
 * {@code helper.exists(name, PackType.CLIENT_RESOURCES, ".ogg", "sounds")} on every
 * {@code SOUND}-type entry and throws
 * {@code IllegalStateException("Found invalid sound events: ...")} when the file is absent
 * -- so a placeholder pointing at a file that does not exist yet would hard-fail
 * {@code runData}. {@code EVENT}-type entries are validated against
 * {@code BuiltInRegistries.SOUND_EVENT} instead (same class, {@code validateEvent}), which
 * is why this scaffolding survives having no audio at all.
 *
 * <p><b>Serialization note.</b> {@code SoundDefinition.Sound#serialize} strips the
 * {@code minecraft:} namespace via {@code stripMcPrefix}, so these come out as
 * {@code {"name": "entity.spider.step", "type": "event"}} -- a bare path, which the client
 * re-parses back into the {@code minecraft} namespace. Mod-namespaced names keep their
 * prefix.
 */
public class ModSoundDefinitionsProvider extends SoundDefinitionsProvider {
    public ModSoundDefinitionsProvider(PackOutput output, ExistingFileHelper existingFileHelper) {
        super(output, Formicary.MODID, existingFileHelper);
    }

    @Override
    public void registerSounds() {
        // ---------------------------------------------------------- worker ant --
        // Play-test round 8: the single 2.85s ambient became three ~1.1s cuts, and the
        // hurt/death redirects became real files derived from the same recording. All of
        // them are GENERATED by assets-src/sounds.py -- see this class's javadoc.
        voice(ModSounds.WORKER_ANT_AMBIENT, "worker_ant", "ambient", "ambient1", "ambient2", "ambient3");
        voice(ModSounds.WORKER_ANT_HURT, "worker_ant", "hurt", "hurt1", "hurt2");
        voice(ModSounds.WORKER_ANT_DEATH, "worker_ant", "death", "death");

        // --------------------------------------------------------- soldier ant --
        voice(ModSounds.SOLDIER_ANT_AMBIENT, "soldier_ant", "ambient", "ambient1", "ambient2", "ambient3");
        voice(ModSounds.SOLDIER_ANT_HURT, "soldier_ant", "hurt", "hurt1", "hurt2");
        voice(ModSounds.SOLDIER_ANT_DEATH, "soldier_ant", "death", "death");

        // --------------------------------------------------------------- larva --
        borrow(ModSounds.LARVA_HURT, SoundEvents.SLIME_SQUISH_SMALL, "larva.hurt");
        borrow(ModSounds.LARVA_DEATH, SoundEvents.SLIME_SQUISH_SMALL, "larva.death");

        // ----------------------------------------------------------- ender ant --
        borrow(ModSounds.ENDER_ANT_AMBIENT, SoundEvents.ENDERMAN_AMBIENT, "ender_ant.ambient");
        borrow(ModSounds.ENDER_ANT_HURT, SoundEvents.ENDERMAN_HURT, "ender_ant.hurt");
        borrow(ModSounds.ENDER_ANT_DEATH, SoundEvents.ENDERMAN_DEATH, "ender_ant.death");
        borrow(ModSounds.ENDER_ANT_TELEPORT, SoundEvents.ENDERMAN_TELEPORT, "ender_ant.teleport");

        // --------------------------------------------------------------- queen --
        // Note this ambient event has TWO call sites: QueenAntEntity#getAmbientSound (the
        // idle voice) and the phase-transition burst, which plays the same event at
        // volume 2.0 / pitch 0.5 -- so whichever of the three variants the game picks is
        // heard both as her idle and, pitched down, as her phase change. That is why her
        // cuts are longer than the workers' and her rate variation is the narrowest of the
        // three (assets-src/sounds.py, VOICES["queen"]).
        voice(ModSounds.QUEEN_AMBIENT, "queen", "ambient", "ambient1", "ambient2", "ambient3");
        voice(ModSounds.QUEEN_HURT, "queen", "hurt", "hurt1", "hurt2");
        voice(ModSounds.QUEEN_DEATH, "queen", "death", "death");
        borrow(ModSounds.QUEEN_ROAR, SoundEvents.WARDEN_ROAR, "queen.roar");
        borrow(ModSounds.QUEEN_ACID_SPIT, SoundEvents.LLAMA_SPIT, "queen.acid_spit");
        borrow(ModSounds.QUEEN_BURROW, SoundEvents.ROOTED_DIRT_BREAK, "queen.burrow");
        // GENERIC_EXPLODE is one of the few SoundEvents fields that is a
        // Holder.Reference<SoundEvent> rather than a bare SoundEvent (it is registered with
        // registerForHolder), so it needs .value() to reach the event itself.
        borrow(ModSounds.QUEEN_SLAM, SoundEvents.GENERIC_EXPLODE.value(), "queen.slam");
    }

    /**
     * Defines {@code event} as one or more real {@code .ogg} files under
     * {@code assets/formicary/sounds/entity/<mob>/}, subtitled
     * {@code subtitles.formicary.<mob>.<subtitle>}.
     *
     * <p>Passing more than one file is how a voice gets variation: the client picks
     * between the listed sounds at random on every play (they carry equal weight unless
     * one is given {@code .weight(...)}), and then applies the caller's own pitch
     * randomisation on top. That is why the generator makes three ambients from three
     * different stretches of the recording rather than one file played three ways.
     *
     * <p>Every file named here must exist before {@code runData}: unlike the
     * {@link #borrow} redirects, {@code SoundType.SOUND} entries are validated against the
     * filesystem, so a typo in one of these names fails datagen rather than shipping a
     * silent mob. Run {@code assets-src/sounds.py} first.
     */
    private void voice(Supplier<SoundEvent> event, String mob, String subtitle, String... files) {
        SoundDefinition.Sound[] sounds = new SoundDefinition.Sound[files.length];
        for (int i = 0; i < files.length; i++) {
            sounds[i] = sound(Formicary.MODID + ":entity/" + mob + "/" + files[i]);
        }
        add(event, definition()
                .subtitle("subtitles.formicary." + mob + "." + subtitle)
                .with(sounds));
    }

    /**
     * Defines {@code event} as a redirect to {@code vanilla}, subtitled
     * {@code subtitles.formicary.<subtitleKey>}.
     *
     * <p>Replace a call to this with {@link #voice} once real files exist.
     */
    private void borrow(Supplier<SoundEvent> event, SoundEvent vanilla, String subtitleKey) {
        // getLocation() is the event's *sound* location, which for every vanilla constant
        // borrowed here is also its registry key -- SoundEvents.register(String name) is
        // register(name, name) -> createVariableRangeEvent(location). The registry key is
        // what SoundDefinitionsProvider#validateEvent looks up.
        add(event, definition()
                .subtitle("subtitles.formicary." + subtitleKey)
                .with(sound(vanilla.getLocation(), SoundDefinition.SoundType.EVENT)));
    }
}
