package com.nogal.formicary.sound;

import com.nogal.formicary.Formicary;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

/**
 * Every mob voice in the mod, as sound events the mod owns.
 *
 * <p><b>Why this exists.</b> Until now each mob called a vanilla {@code SoundEvents}
 * constant directly, so "give the queen her own roar" meant editing Java. These
 * registrations put one layer of indirection in the way: the entities now play
 * {@code formicary:entity.queen.roar}, and what that <em>actually sounds like</em> is
 * decided in {@code sounds.json}, which is generated by
 * {@link com.nogal.formicary.datagen.ModSoundDefinitionsProvider}. Today every entry
 * there is a {@code type: "event"} redirect to the vanilla sound the mob used to call, so
 * the mod is byte-identical in-game with zero {@code .ogg} files shipped. Dropping a real
 * file in later is a one-line edit in that provider plus {@code .\gradlew runData} -- no
 * Java change, no recompile. The walkthrough is {@code docs/SOUNDS.md}.
 *
 * <p><b>Naming.</b> Ids follow the vanilla convention, {@code entity.<mob>.<voice>}
 * (verified in the decompiled {@code SoundEvents.java}: {@code SPIDER_STEP =
 * register("entity.spider.step")}). Tamed ants deliberately share their wild caste's
 * events -- a tamed worker is still a worker, and giving it a separate voice would double
 * the number of files Logan has to author for no audible gain.
 *
 * <p><b>Shape.</b> {@code SoundEvent.createVariableRangeEvent(ResourceLocation)} is the
 * same factory vanilla uses for all of these (its {@code register(ResourceLocation name)}
 * is {@code register(name, name)} -> {@code createVariableRangeEvent(location)}), so the
 * event's sound location is its own registry id -- which is exactly what the client looks
 * up in {@code sounds.json}. Verified public from outside the package at
 * {@code NeoForgeMod.java:629}.
 */
public final class ModSounds {
    public static final DeferredRegister<SoundEvent> SOUND_EVENTS =
            DeferredRegister.create(Registries.SOUND_EVENT, Formicary.MODID);

    // ------------------------------------------------------------ worker ant --
    // Shared with TamedWorkerAntEntity.

    /** Borrows {@code SoundEvents.SPIDER_STEP}. */
    public static final DeferredHolder<SoundEvent, SoundEvent> WORKER_ANT_AMBIENT =
            register("entity.worker_ant.ambient");
    /** Borrows {@code SoundEvents.SPIDER_HURT}. */
    public static final DeferredHolder<SoundEvent, SoundEvent> WORKER_ANT_HURT =
            register("entity.worker_ant.hurt");
    /** Borrows {@code SoundEvents.SPIDER_DEATH}. */
    public static final DeferredHolder<SoundEvent, SoundEvent> WORKER_ANT_DEATH =
            register("entity.worker_ant.death");

    // ----------------------------------------------------------- soldier ant --
    // Shared with TamedSoldierAntEntity.

    /** Borrows {@code SoundEvents.SPIDER_AMBIENT}. */
    public static final DeferredHolder<SoundEvent, SoundEvent> SOLDIER_ANT_AMBIENT =
            register("entity.soldier_ant.ambient");
    /** Borrows {@code SoundEvents.SPIDER_HURT}. */
    public static final DeferredHolder<SoundEvent, SoundEvent> SOLDIER_ANT_HURT =
            register("entity.soldier_ant.hurt");
    /** Borrows {@code SoundEvents.SPIDER_DEATH}. */
    public static final DeferredHolder<SoundEvent, SoundEvent> SOLDIER_ANT_DEATH =
            register("entity.soldier_ant.death");

    // ----------------------------------------------------------------- larva --
    // No ambient on purpose: LarvaEntity overrides no getAmbientSound, so a grub is silent
    // until something touches it.

    /** Borrows {@code SoundEvents.SLIME_SQUISH_SMALL}. */
    public static final DeferredHolder<SoundEvent, SoundEvent> LARVA_HURT =
            register("entity.larva.hurt");
    /** Borrows {@code SoundEvents.SLIME_SQUISH_SMALL}. */
    public static final DeferredHolder<SoundEvent, SoundEvent> LARVA_DEATH =
            register("entity.larva.death");

    // ------------------------------------------------------------- ender ant --

    /** Borrows {@code SoundEvents.ENDERMAN_AMBIENT}. */
    public static final DeferredHolder<SoundEvent, SoundEvent> ENDER_ANT_AMBIENT =
            register("entity.ender_ant.ambient");
    /** Borrows {@code SoundEvents.ENDERMAN_HURT}. */
    public static final DeferredHolder<SoundEvent, SoundEvent> ENDER_ANT_HURT =
            register("entity.ender_ant.hurt");
    /** Borrows {@code SoundEvents.ENDERMAN_DEATH}. */
    public static final DeferredHolder<SoundEvent, SoundEvent> ENDER_ANT_DEATH =
            register("entity.ender_ant.death");
    /** Borrows {@code SoundEvents.ENDERMAN_TELEPORT}. */
    public static final DeferredHolder<SoundEvent, SoundEvent> ENDER_ANT_TELEPORT =
            register("entity.ender_ant.teleport");

    // ----------------------------------------------------------------- queen --

    /** Borrows {@code SoundEvents.SPIDER_AMBIENT}. */
    public static final DeferredHolder<SoundEvent, SoundEvent> QUEEN_AMBIENT =
            register("entity.queen.ambient");
    /** Borrows {@code SoundEvents.SPIDER_HURT}. */
    public static final DeferredHolder<SoundEvent, SoundEvent> QUEEN_HURT =
            register("entity.queen.hurt");
    /** Borrows {@code SoundEvents.SPIDER_DEATH}. */
    public static final DeferredHolder<SoundEvent, SoundEvent> QUEEN_DEATH =
            register("entity.queen.death");
    /** Frenzy unlock. Borrows {@code SoundEvents.WARDEN_ROAR}. */
    public static final DeferredHolder<SoundEvent, SoundEvent> QUEEN_ROAR =
            register("entity.queen.roar");
    /** Ranged attack. Borrows {@code SoundEvents.LLAMA_SPIT}. */
    public static final DeferredHolder<SoundEvent, SoundEvent> QUEEN_ACID_SPIT =
            register("entity.queen.acid_spit");
    /**
     * Both halves of the burrow move -- going under and coming back up. Borrows
     * {@code SoundEvents.ROOTED_DIRT_BREAK}; the surfacing call site used to borrow
     * {@code ROOTED_DIRT_PLACE} instead, and now plays this same event at its own quieter
     * volume/pitch, so one file covers both.
     */
    public static final DeferredHolder<SoundEvent, SoundEvent> QUEEN_BURROW =
            register("entity.queen.burrow");
    /** Burrow eruption. Borrows {@code SoundEvents.GENERIC_EXPLODE}. */
    public static final DeferredHolder<SoundEvent, SoundEvent> QUEEN_SLAM =
            register("entity.queen.slam");

    private static DeferredHolder<SoundEvent, SoundEvent> register(String path) {
        return SOUND_EVENTS.register(path, (ResourceLocation id) -> SoundEvent.createVariableRangeEvent(id));
    }

    private ModSounds() {
    }
}
